# Generated by Django 5.2.1 on 2025-05-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='employee_id',
        ),
    ]
