# Generated by Django 5.2.1 on 2025-05-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='lending',
            name='equipment',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
        migrations.DeleteModel(
            name='Archive',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Lending',
        ),
    ]
