# Generated by Django 5.2.1 on 2025-05-22 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_reason', models.TextField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='supplies.item')),
            ],
        ),
    ]
